- demo-data/referencedata.program_orderables.json
> Update MaxStock to 3 for all

- src/integration-test/java/org/openlmis/referencedata/repository/FacilityRepositoryIntegrationTest.java
- src/integration-test/java/org/openlmis/referencedata/web/FacilityControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/domain/Facility.java
- src/main/java/org/openlmis/referencedata/dto/FacilityDto.java
- src/main/java/org/openlmis/referencedata/repository/FacilityRepository.java
- src/main/java/org/openlmis/referencedata/service/FacilityService.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/FacilityMessageKeys.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/MessageKeys.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
- src/main/resources/api-definition.yaml
- src/main/resources/db/migration/20170327131236620__add_extradata_to_facility.sql
- src/main/resources/messages_en.properties
- src/main/resources/schemas/facilityQueryDto.json
- src/test/java/org/openlmis/referencedata/service/FacilityServiceTest.java
The commit adds a new field "extraData" to the Facility entity.
This follows the pattern established by the extraData in the User entity.
The extraData is a map, the search has been adjusted to accept extraData
as a parameter. Small refactor was done and tests were added.
Please kindly review and provide feedback if something needs to be improved.
> Added extraData to Facility entity

- src/integration-test/java/org/openlmis/referencedata/web/UserControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/domain/Facility.java
- src/main/java/org/openlmis/referencedata/domain/SupervisoryNode.java
- src/test/java/org/openlmis/referencedata/domain/FacilityTest.java
- src/test/java/org/openlmis/referencedata/domain/SupervisionRoleAssignmentTest.java
- src/test/java/org/openlmis/referencedata/domain/SupervisoryNodeTest.java
- src/test/java/org/openlmis/referencedata/domain/UserTest.java
refer to: https://openlmis.atlassian.net/browse/OLMIS-2536
> OLMIS-2536: Added check if facility supports program

- demo-data/referencedata.role_assignments.json
- demo-data/referencedata.role_rights.json
- demo-data/referencedata.roles.json
refer to: https://openlmis.atlassian.net/browse/OLMIS-2519
> OLMIS-2519: create role only can view stock cards and assign to wclerk1

- src/integration-test/java/org/openlmis/referencedata/repository/FacilityTypeApprovedProductRepositoryTest.java
- src/integration-test/java/org/openlmis/referencedata/web/FacilityTypeApprovedProductControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/repository/custom/FacilityTypeApprovedProductRepositoryCustom.java
- src/main/java/org/openlmis/referencedata/repository/custom/impl/FacilityTypeApprovedProductRepositoryImpl.java
- src/main/java/org/openlmis/referencedata/service/FacilityTypeApprovedProductService.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/FacilityTypeApprovedProductMessageKeys.java
- src/main/java/org/openlmis/referencedata/web/FacilityTypeApprovedProductController.java
- src/main/resources/api-definition.yaml
- src/main/resources/messages_en.properties
- src/main/resources/schemas/approvedProductQueryDto.json
- src/test/java/org/openlmis/referencedata/service/FacilityTypeApprovedProductServiceTest.java
The facilityType is required while searching for FTAPs and the program is optional. The endpoint allows retrieving all approved products that match the search criteria.
> Added FTAP search by facility type and program

- demo-data/referencedata.facilities.json
> OLMIS-4337 escaping single quotes in facilities, which were causing

- CHANGELOG.md
- src/main/java/org/openlmis/referencedata/web/OrderableFulfillController.java
- src/main/java/org/openlmis/referencedata/web/OrderableFulfillFactory.java
I've added some additional profiler so we could detect the most problematic places in the endpoint.
> OLMIS-6384: Added new Profilers to detect most problematic places

- CHANGELOG.md
- src/main/java/org/openlmis/referencedata/domain/Orderable.java
- src/main/java/org/openlmis/referencedata/domain/ProgramOrderable.java
- src/main/java/org/openlmis/referencedata/repository/ProgramOrderableRepository.java
- src/main/java/org/openlmis/referencedata/service/DataExportService.java
- src/main/java/org/openlmis/referencedata/service/ProgramOrderableService.java
- src/main/java/org/openlmis/referencedata/web/csv/processor/CsvCellProcessors.java
- src/main/java/org/openlmis/referencedata/web/csv/processor/FormatMoney.java
- src/main/java/org/openlmis/referencedata/web/csv/processor/FormatOrderable.java
- src/main/java/org/openlmis/referencedata/web/csv/processor/FormatOrderableDisplayCategory.java
- src/main/java/org/openlmis/referencedata/web/csv/processor/FormatProgram.java
- src/test/java/org/openlmis/referencedata/service/CsvFormatterServiceTest.java
- src/test/java/org/openlmis/referencedata/service/DataExportServiceTest.java
- src/test/java/org/openlmis/referencedata/service/OrderableServiceTest.java
- src/test/java/org/openlmis/referencedata/service/ProgramOrderableServiceTest.java
- src/test/java/org/openlmis/referencedata/web/csv/processor/FormatMoneyTest.java
- src/test/java/org/openlmis/referencedata/web/csv/processor/FormatOrderableDisplayCategoryTest.java
- src/test/java/org/openlmis/referencedata/web/csv/processor/FormatOrderableTest.java
- src/test/java/org/openlmis/referencedata/web/csv/processor/FormatProgramTest.java
Added ImportField annotation in ProgramOrderable class 
Added formatters for Money, Orderable, OrderableDisplayCategory and Program types 
Added ProgramOrderableRepository and ProgramOrderableService 
Added test classes
Updated CHANGELOG.md
Details about task: https://openlmis.atlassian.net/browse/OLMIS-7646
> OLMIS-7646: Added programOrderable.csv generation functionality

- CHANGELOG.md
- src/main/java/org/openlmis/referencedata/domain/Orderable.java
- src/main/java/org/openlmis/referencedata/dto/OrderableIdentifierCsvModel.java
- src/main/java/org/openlmis/referencedata/repository/OrderableRepository.java
- src/main/java/org/openlmis/referencedata/service/OrderableIdentifierService.java
- src/test/java/org/openlmis/referencedata/service/OrderableIdentifierServiceTest.java
Added OrderableIdentifierCsvModel class
Added native query for retrieving OrderableIdentifierCsvModel data 
Added OrderableIdentifierService class
Updated CHANGELOG.md
Jira task link: https://openlmis.atlassian.net/browse/OLMIS-7645
> OLMIS-7645: Added orderableIdentifier.csv generation functionality

- CHANGELOG.md
- src/main/java/org/openlmis/referencedata/domain/TradeItem.java
- src/main/java/org/openlmis/referencedata/dto/TradeItemCsvModel.java
- src/main/java/org/openlmis/referencedata/repository/TradeItemRepository.java
- src/main/java/org/openlmis/referencedata/service/TradeItemService.java
- src/test/java/org/openlmis/referencedata/service/TradeItemServiceTest.java
Added TradeItemCsvModel class
Added native query for retrieving TradeItemCsvModel data 
Added TradeItemService class
Updated CHANGELOG.md
Jira task link: https://openlmis.atlassian.net/browse/OLMIS-7647
> OLMIS-7647: Added tradeItem.csv generation functionality

- CHANGELOG.md
- src/integration-test/java/org/openlmis/referencedata/web/FacilityControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
- src/main/resources/api-definition.yaml
JIRA task link: https://openlmis.atlassian.net/browse/OLMIS-7718
> OLMIS-7718: Added GET api/facilities/full endpoint

- build.gradle
* added lombok annotation processor and fixed jacocoTestReport
* now we can run unit tests through Intellij
> AO-759: Fixed gradle build

- .gitignore
- CHANGELOG.md
- src/main/java/org/openlmis/referencedata/web/DataExportController.java
- src/main/java/org/openlmis/referencedata/web/DataImportController.java
- src/main/resources/api-definition.yaml
- src/test/java/org/openlmis/referencedata/web/DataImportControllerTest.java
The aim of this ticket is to create an empty controller for data import
Jira ticket: https://openlmis.atlassian.net/browse/OLMIS-7670
> OLMIS-7670: Add data import endpoint

- CHANGELOG.md
- src/main/java/org/openlmis/referencedata/service/DataImportService.java
- src/main/java/org/openlmis/referencedata/util/FileHelper.java
- src/test/java/org/openlmis/referencedata/util/FileHelperTest.java
Jira task link: https://openlmis.atlassian.net/browse/OLMIS-7671
> OLMIS-7671: Added DataImportService and FileHelper classes

- src/main/java/org/openlmis/referencedata/web/DataImportController.java
It resolves sonar's quality gate error, making build unstable
> OLMIS-7670: Removed generic wildcard type from controller

- src/integration-test/java/org/openlmis/referencedata/web/OrderableControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/domain/PriceChange.java
- src/main/java/org/openlmis/referencedata/domain/ProgramOrderable.java
- src/main/java/org/openlmis/referencedata/dto/PriceChangeDto.java
- src/main/java/org/openlmis/referencedata/dto/ProgramOrderableDto.java
- src/main/java/org/openlmis/referencedata/service/export/ProgramOrderableImportPersister.java
- src/main/java/org/openlmis/referencedata/util/OrderableBuilder.java
- src/main/resources/db/migration/20231111221730515__add_price_changes_table.sql
- src/test/java/org/openlmis/referencedata/domain/PriceChangeTest.java
- src/test/java/org/openlmis/referencedata/dto/PriceChangeDtoTest.java
- src/test/java/org/openlmis/referencedata/testbuilder/PriceChangeDataBuilder.java
- src/test/java/org/openlmis/referencedata/testbuilder/ProgramOrderableDataBuilder.java
- src/test/java/org/openlmis/referencedata/util/OrderableBuilderTest.java
Jira task link: https://openlmis.atlassian.net/browse/AO-802
> AO-802: Added product price change tracking

- src/integration-test/java/org/openlmis/referencedata/web/OrderableControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/domain/Orderable.java
- src/main/java/org/openlmis/referencedata/dto/OrderableDto.java
- src/main/resources/db/migration/20240512102738466__add_quarantined_column_to_orderables_table.sql
- src/main/resources/schemas/orderable.json
- src/test/java/org/openlmis/referencedata/testbuilder/OrderableDataBuilder.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-120
> OAM-120: Added quarantined field to Orderable entity

- src/integration-test/java/org/openlmis/referencedata/web/LotControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/domain/Lot.java
- src/main/java/org/openlmis/referencedata/dto/LotDto.java
- src/main/resources/db/migration/20240512111602459__add_quarantined_column_to_lots_table.sql
- src/main/resources/schemas/lot.json
- src/test/java/org/openlmis/referencedata/dto/LotDtoTest.java
- src/test/java/org/openlmis/referencedata/testbuilder/LotDataBuilder.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-121
> OAM-121: Added quarantined field to Lot entity

- src/integration-test/java/org/openlmis/referencedata/repository/OrderableRepositoryIntegrationTest.java
- src/integration-test/java/org/openlmis/referencedata/web/OrderableControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/repository/OrderableRepository.java
- src/main/java/org/openlmis/referencedata/repository/RepositoryConstants.java
- src/main/java/org/openlmis/referencedata/repository/custom/OrderableRepositoryCustom.java
- src/main/java/org/openlmis/referencedata/repository/custom/impl/OrderableRepositoryImpl.java
- src/main/java/org/openlmis/referencedata/web/OrderableSearchParams.java
- src/main/java/org/openlmis/referencedata/web/QueryOrderableSearchParams.java
- src/test/java/org/openlmis/referencedata/web/OrderableSearchParamsTest.java
- src/test/java/org/openlmis/referencedata/web/QueryOrderableSearchParamsTest.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-124
> OAM-124: Added includeQuarantined search param for Orderables

- src/integration-test/java/org/openlmis/referencedata/repository/LotRepositoryIntegrationTest.java
- src/integration-test/java/org/openlmis/referencedata/web/LotControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/repository/custom/LotRepositoryCustom.java
- src/main/java/org/openlmis/referencedata/repository/custom/impl/LotRepositoryImpl.java
- src/main/java/org/openlmis/referencedata/service/LotSearchParams.java
- src/main/java/org/openlmis/referencedata/service/LotService.java
- src/main/resources/api-definition.yaml
- src/test/java/org/openlmis/referencedata/service/LotServiceTest.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-125
> OAM-125: Added includeQuarantined param for GET api/lots endpoint

- src/integration-test/java/org/openlmis/referencedata/repository/GeographicLevelRepositoryIntegrationTest.java
- src/main/resources/db/migration/20240529100408520__add_wards_services_configuration.sql
JIRA task link: https://openlmis.atlassian.net/browse/OAM-48
> OAM-48: Added ward/service configuration script

- src/integration-test/java/org/openlmis/referencedata/web/UserControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/UserMessageKeys.java
- src/main/java/org/openlmis/referencedata/validate/UserValidator.java
- src/main/resources/messages_en.properties
- src/test/java/org/openlmis/referencedata/validate/UserValidatorTest.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-186
> OAM-186: Added home facility validation for ward/service type

- src/integration-test/java/org/openlmis/referencedata/repository/FacilityRepositoryIntegrationTest.java
- src/main/java/org/openlmis/referencedata/repository/FacilityTypeRepository.java
- src/main/java/org/openlmis/referencedata/repository/custom/FacilityRepositoryCustom.java
- src/main/java/org/openlmis/referencedata/repository/custom/impl/FacilityRepositoryImpl.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
- src/main/java/org/openlmis/referencedata/web/FacilitySearchParams.java
- src/main/resources/api-definition.yaml
- src/test/java/org/openlmis/referencedata/web/FacilitySearchParamsTest.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-195
> OAM-195: Added excludeWardsServices for facilities searching endpoints

- src/main/java/org/openlmis/referencedata/domain/SupportedProgram.java
- src/main/java/org/openlmis/referencedata/repository/FacilityRepository.java
- src/main/java/org/openlmis/referencedata/service/FacilityService.java
- src/main/java/org/openlmis/referencedata/service/FacilityTypeService.java
- src/main/java/org/openlmis/referencedata/service/stockmanagement/Node.java
- src/main/java/org/openlmis/referencedata/service/stockmanagement/ValidAssignmentDto.java
- src/main/java/org/openlmis/referencedata/service/stockmanagement/ValidSourceDestinationService.java
- src/main/java/org/openlmis/referencedata/service/stockmanagement/ValidSourceDestinationStockManagementService.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/FacilityMessageKeys.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/MessageKeys.java
- src/main/java/org/openlmis/referencedata/util/messagekeys/stockmanagement/ValidAssignmentMessageKeys.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
- src/main/resources/application.properties
- src/main/resources/messages_en.properties
Auto supported programs import.
Auto valid source and valid destination creation.
JIRA task link: https://openlmis.atlassian.net/browse/OAM-206
> OAM-206: Added configuration import for creating Ward/Service.

- src/main/java/org/openlmis/referencedata/repository/GeographicLevelRepository.java
- src/main/java/org/openlmis/referencedata/service/FacilityBuilder.java
- src/main/resources/db/migration/20240617152204384__add_order_delete_right.sql
- src/test/java/org/openlmis/referencedata/service/FacilityBuilderTest.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-220
> OAM-220: Added creating new geo zone for new facility

- src/main/java/org/openlmis/referencedata/service/FacilityBuilder.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-235
> OAM-235: Adapted facility update endpoint for ward/service configuration

- src/main/java/org/openlmis/referencedata/service/FacilityBuilder.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-235
> OAM-235: Restored @Transactional, added not null condition

- Jenkinsfile
- build.sh
- docker-compose.builder.yml
- docker-compose.override.yml
JIRA task link: https://openlmis.atlassian.net/browse/OIS-14
> OIS-14: Upgrade Transifex API

- src/integration-test/java/org/openlmis/referencedata/web/FacilityControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-251
> OAM-251: Update facilities delete endpoint for wards/services

- src/main/resources/db/migration/20240730220255434__add_not_null_constraint.sql
JIRA task link: https://openlmis.atlassian.net/browse/OAM-260
> OAM-260: Added not null constraints to orderable_units_assignment table

- src/integration-test/java/org/openlmis/referencedata/web/FacilityControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/service/FacilityBuilder.java
- src/test/java/org/openlmis/referencedata/service/FacilityBuilderTest.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-265
> OAM-265: Modified PUT api/facilities endpoint to update geozone

- src/main/resources/db/migration/20241011221730514__add_dhis2_integration_rights.sql
JIRA task link: https://openlmis.atlassian.net/browse/OLMIS-8005
> OLMIS-8005: Added DHIS2 Integration rights

- src/integration-test/java/org/openlmis/referencedata/web/FacilityControllerIntegrationTest.java
- src/main/java/org/openlmis/referencedata/repository/RequisitionGroupRepository.java
- src/main/java/org/openlmis/referencedata/web/FacilityController.java
JIRA task link: https://openlmis.atlassian.net/browse/OAM-251
> OAM-251: Updated DELETE facilities endpoint for wards/services

- performance/config.yml
- performance/tests/approvedProducts.yml
- performance/tests/approvedProductsForEssentialMedsAndDistrictHospital.yml
- performance/tests/facilities.yml
- performance/tests/facilityTypeApprovedProducts.yml
- performance/tests/facilityUpdateAsync.yml
- performance/tests/idealStockAmounts.yml
- performance/tests/orderables.yml
- performance/tests/processingPeriods.yml
- performance/tests/programs.yml
- performance/tests/supervisoryNodes.yml
- performance/tests/supplyLines.yml
- performance/tests/users.yml
Deleted default value that are not set in the jenkins job build, it caused issue that stops the performance tests.
> CQI-21: added missing default values

- build.gradle
- Added integration tests to Jacoco tests coverage. 
- Fixed indentations.
> Add integration tests to jacoco coverage
